per_listener_settings false
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

listener 8883 0.0.0.0
allow_anonymous false
certfile /mosquitto/tls/server.crt
keyfile /mosquitto/tls/server.key
tls_version tlsv1.2
retain_available false
message_size_limit 2048
