CREATE TABLE authentication_attempt_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempted_username VARCHAR(255) NOT NULL,
    authenticated_user_id BIGINT,
    outcome VARCHAR(7) NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_authentication_attempt_username
        CHECK (length(btrim(attempted_username)) > 0),
    CONSTRAINT chk_authentication_attempt_outcome
        CHECK (outcome IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT chk_authentication_attempt_user
        CHECK (
            (outcome = 'SUCCESS' AND authenticated_user_id IS NOT NULL)
            OR (outcome = 'FAILURE' AND authenticated_user_id IS NULL)
        )
);

CREATE INDEX idx_authentication_attempts_at_id
    ON authentication_attempt_audits (attempted_at DESC, id DESC);

CREATE INDEX idx_authentication_attempts_username_at_id
    ON authentication_attempt_audits (lower(attempted_username), attempted_at DESC, id DESC);

CREATE TRIGGER authentication_attempt_audits_append_only
    BEFORE UPDATE OR DELETE ON authentication_attempt_audits
    FOR EACH ROW EXECUTE FUNCTION reject_audit_history_mutation();
