CREATE TABLE device_credential_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    previous_signing_key_fingerprint VARCHAR(64),
    new_signing_key_fingerprint VARCHAR(64) NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    changed_by_username VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_credential_audits_device FOREIGN KEY (device_id)
        REFERENCES devices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_credential_audits_actor FOREIGN KEY (changed_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_device_credential_audits_operation
        CHECK (operation IN ('PROVISION', 'ROTATE')),
    CONSTRAINT ck_device_credential_audits_previous_fingerprint
        CHECK (
            previous_signing_key_fingerprint IS NULL
            OR previous_signing_key_fingerprint ~ '^[0-9a-f]{64}$'
        ),
    CONSTRAINT ck_device_credential_audits_new_fingerprint
        CHECK (new_signing_key_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_device_credential_audits_provision_snapshot
        CHECK (operation <> 'PROVISION' OR previous_signing_key_fingerprint IS NULL)
);

CREATE INDEX ix_device_credential_audits_device_time
    ON device_credential_audits (device_id, changed_at DESC, id DESC);

CREATE INDEX ix_device_credential_audits_actor_time
    ON device_credential_audits (lower(changed_by_username), changed_at DESC, id DESC);

CREATE TRIGGER device_credential_audits_append_only
    BEFORE UPDATE OR DELETE ON device_credential_audits
    FOR EACH ROW EXECUTE FUNCTION reject_audit_history_mutation();
