ALTER TABLE users
    ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN mfa_secret_ciphertext VARCHAR(256),
    ADD COLUMN mfa_pending_secret_ciphertext VARCHAR(256),
    ADD COLUMN mfa_enrollment_expires_at TIMESTAMPTZ,
    ADD COLUMN mfa_last_totp_counter BIGINT NOT NULL DEFAULT -1,
    ADD COLUMN mfa_auth_version INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_users_mfa_active_secret CHECK (
        (mfa_enabled AND mfa_secret_ciphertext IS NOT NULL
            AND mfa_pending_secret_ciphertext IS NULL AND mfa_enrollment_expires_at IS NULL)
        OR (NOT mfa_enabled AND mfa_secret_ciphertext IS NULL)
    ),
    ADD CONSTRAINT ck_users_mfa_pending_expiry CHECK (
        (mfa_pending_secret_ciphertext IS NULL AND mfa_enrollment_expires_at IS NULL)
        OR (NOT mfa_enabled AND mfa_pending_secret_ciphertext IS NOT NULL
            AND mfa_enrollment_expires_at IS NOT NULL)
    ),
    ADD CONSTRAINT ck_users_mfa_counter CHECK (mfa_last_totp_counter >= -1),
    ADD CONSTRAINT ck_users_mfa_auth_version CHECK (mfa_auth_version >= 0);

CREATE TABLE mfa_recovery_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMPTZ,
    CONSTRAINT fk_mfa_recovery_codes_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_mfa_recovery_codes_hash CHECK (code_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT uq_mfa_recovery_codes_user_hash UNIQUE (user_id, code_hash)
);

CREATE INDEX ix_mfa_recovery_codes_unused
    ON mfa_recovery_codes (user_id, id) WHERE used_at IS NULL;

CREATE TABLE mfa_login_challenges (
    id VARCHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT fk_mfa_login_challenges_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_mfa_login_challenges_expiry ON mfa_login_challenges (expires_at);

CREATE TABLE mfa_security_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mfa_security_audits_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_mfa_security_audits_operation CHECK (
        operation IN ('ENROLLMENT_STARTED', 'ENABLED', 'DISABLED', 'RECOVERY_CODE_USED')
    )
);

CREATE INDEX ix_mfa_security_audits_changed_at
    ON mfa_security_audits (changed_at DESC, id DESC);
CREATE INDEX ix_mfa_security_audits_username_changed_at
    ON mfa_security_audits (lower(username), changed_at DESC, id DESC);
CREATE INDEX ix_mfa_security_audits_operation_changed_at
    ON mfa_security_audits (operation, changed_at DESC, id DESC);

CREATE TRIGGER mfa_security_audits_append_only
    BEFORE UPDATE OR DELETE ON mfa_security_audits
    FOR EACH ROW EXECUTE FUNCTION reject_audit_history_mutation();
