CREATE TABLE user_account_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(32) NOT NULL,
    target_user_id BIGINT NOT NULL,
    target_username VARCHAR(50) NOT NULL,
    previous_role VARCHAR(30) NOT NULL,
    new_role VARCHAR(30) NOT NULL,
    previous_enabled BOOLEAN NOT NULL,
    new_enabled BOOLEAN NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_username VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_account_audits_target FOREIGN KEY (target_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_account_audits_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_account_audits_operation CHECK (operation IN ('ACCOUNT_UPDATED')),
    CONSTRAINT ck_user_account_audits_previous_role CHECK (
        previous_role IN ('ADMIN', 'SECURITY_ANALYST', 'USER', 'DEVICE')
    ),
    CONSTRAINT ck_user_account_audits_new_role CHECK (
        new_role IN ('ADMIN', 'SECURITY_ANALYST', 'USER', 'DEVICE')
    )
);

CREATE INDEX ix_user_account_audits_changed_at
    ON user_account_audits (changed_at DESC, id DESC);
CREATE INDEX ix_user_account_audits_target_changed_at
    ON user_account_audits (lower(target_username), changed_at DESC, id DESC);
CREATE INDEX ix_user_account_audits_actor_changed_at
    ON user_account_audits (lower(actor_username), changed_at DESC, id DESC);

CREATE TRIGGER user_account_audits_append_only
    BEFORE UPDATE OR DELETE ON user_account_audits
    FOR EACH ROW EXECUTE FUNCTION reject_audit_history_mutation();
