CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code VARCHAR(64) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    device_type VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    mqtt_client_id VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ,
    CONSTRAINT uk_devices_device_code UNIQUE (device_code),
    CONSTRAINT uk_devices_mqtt_client_id UNIQUE (mqtt_client_id),
    CONSTRAINT ck_devices_type CHECK (device_type IN ('SENSOR', 'CAMERA', 'ACTUATOR', 'GATEWAY')),
    CONSTRAINT ck_devices_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'REVOKED')),
    CONSTRAINT fk_devices_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_devices_owner_id ON devices (owner_id);
CREATE INDEX ix_devices_status ON devices (status);
