CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    subject VARCHAR(50) NOT NULL,
    resource VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL,
    effect VARCHAR(10) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_policies_name UNIQUE (name),
    CONSTRAINT ck_policies_action CHECK (action IN ('READ', 'WRITE', 'EXECUTE')),
    CONSTRAINT ck_policies_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

CREATE INDEX ix_policies_match ON policies (subject, resource, action, enabled);

INSERT INTO policies (name, subject, resource, action, effect, enabled, description)
VALUES
    ('Sensor Read Data', 'SENSOR', 'sensor-data', 'READ', 'ALLOW', TRUE,
     'Allow sensor devices to read sensor data'),
    ('Camera Read Stream', 'CAMERA', 'camera-stream', 'READ', 'ALLOW', TRUE,
     'Allow camera devices to read their stream'),
    ('Sensor Cannot Write Camera', 'SENSOR', 'camera-stream', 'WRITE', 'DENY', TRUE,
     'Explicitly deny sensors from writing to camera streams')
ON CONFLICT (name) DO NOTHING;
