CREATE TABLE access_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT,
    requester_username VARCHAR(100) NOT NULL,
    requester_role VARCHAR(30) NOT NULL,
    channel VARCHAR(10) NOT NULL,
    device_id BIGINT,
    device_code VARCHAR(64) NOT NULL,
    device_type VARCHAR(20),
    device_status VARCHAR(20),
    resource VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL,
    decision VARCHAR(10) NOT NULL,
    reason VARCHAR(40) NOT NULL,
    matched_policy_id BIGINT,
    matched_policy_name VARCHAR(100),
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_audits_requester FOREIGN KEY (requester_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_access_audits_device FOREIGN KEY (device_id)
        REFERENCES devices (id) ON DELETE SET NULL,
    CONSTRAINT ck_access_audits_role CHECK (requester_role IN ('ADMIN', 'SECURITY_ANALYST', 'USER', 'DEVICE')),
    CONSTRAINT ck_access_audits_channel CHECK (channel IN ('API', 'MQTT')),
    CONSTRAINT ck_access_audits_device_type CHECK (device_type IS NULL OR device_type IN ('SENSOR', 'CAMERA', 'ACTUATOR', 'GATEWAY')),
    CONSTRAINT ck_access_audits_device_status CHECK (device_status IS NULL OR device_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'REVOKED')),
    CONSTRAINT ck_access_audits_action CHECK (action IN ('READ', 'WRITE', 'EXECUTE')),
    CONSTRAINT ck_access_audits_decision CHECK (decision IN ('ALLOW', 'DENY')),
    CONSTRAINT ck_access_audits_reason CHECK (reason IN (
        'POLICY_ALLOW', 'EXPLICIT_DENY', 'NO_MATCHING_POLICY',
        'DEVICE_NOT_FOUND', 'DEVICE_NOT_ACTIVE', 'REQUESTER_ROLE_NOT_ALLOWED'
    ))
);

CREATE INDEX ix_access_audits_evaluated_at ON access_audits (evaluated_at DESC);
CREATE INDEX ix_access_audits_requester_time ON access_audits (requester_id, evaluated_at DESC);
CREATE INDEX ix_access_audits_decision_time ON access_audits (decision, evaluated_at DESC);

CREATE TABLE device_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    metric VARCHAR(64) NOT NULL,
    metric_value NUMERIC(18, 6) NOT NULL,
    unit VARCHAR(16) NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    topic VARCHAR(128) NOT NULL,
    CONSTRAINT fk_device_telemetry_device FOREIGN KEY (device_id)
        REFERENCES devices (id) ON DELETE CASCADE
);

CREATE INDEX ix_device_telemetry_received_at ON device_telemetry (received_at DESC);
CREATE INDEX ix_device_telemetry_device_received ON device_telemetry (device_id, received_at DESC);

INSERT INTO policies (name, subject, resource, action, effect, enabled, description)
VALUES
    ('Sensor Publish Telemetry', 'SENSOR', 'device-telemetry', 'WRITE', 'ALLOW', TRUE,
     'Allow active sensor devices to publish telemetry'),
    ('Camera Publish Telemetry', 'CAMERA', 'device-telemetry', 'WRITE', 'ALLOW', TRUE,
     'Allow active camera devices to publish telemetry')
ON CONFLICT (name) DO NOTHING;
