CREATE TABLE device_ownership_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    previous_owner_id BIGINT NOT NULL,
    previous_owner_username VARCHAR(50) NOT NULL,
    new_owner_id BIGINT NOT NULL,
    new_owner_username VARCHAR(50) NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    changed_by_username VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_ownership_audits_device FOREIGN KEY (device_id)
        REFERENCES devices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_ownership_audits_previous_owner FOREIGN KEY (previous_owner_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_ownership_audits_new_owner FOREIGN KEY (new_owner_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_ownership_audits_actor FOREIGN KEY (changed_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_device_ownership_audits_owner_changed CHECK (previous_owner_id <> new_owner_id)
);

CREATE INDEX ix_device_ownership_audits_device_time
    ON device_ownership_audits (device_id, changed_at DESC, id DESC);
