CREATE TABLE device_status_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    previous_status VARCHAR(20) NOT NULL,
    new_status VARCHAR(20) NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    changed_by_username VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_status_audits_device FOREIGN KEY (device_id)
        REFERENCES devices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_status_audits_actor FOREIGN KEY (changed_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_device_status_audits_previous_status
        CHECK (previous_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'REVOKED')),
    CONSTRAINT ck_device_status_audits_new_status
        CHECK (new_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'REVOKED')),
    CONSTRAINT ck_device_status_audits_status_changed CHECK (previous_status <> new_status)
);

CREATE INDEX ix_device_status_audits_device_time
    ON device_status_audits (device_id, changed_at DESC, id DESC);

CREATE TABLE policy_change_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL,
    operation VARCHAR(10) NOT NULL,
    before_name VARCHAR(100),
    before_subject VARCHAR(50),
    before_resource VARCHAR(100),
    before_action VARCHAR(20),
    before_effect VARCHAR(10),
    before_enabled BOOLEAN,
    before_description VARCHAR(500),
    after_name VARCHAR(100),
    after_subject VARCHAR(50),
    after_resource VARCHAR(100),
    after_action VARCHAR(20),
    after_effect VARCHAR(10),
    after_enabled BOOLEAN,
    after_description VARCHAR(500),
    changed_by_user_id BIGINT NOT NULL,
    changed_by_username VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_policy_change_audits_actor FOREIGN KEY (changed_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_policy_change_audits_operation
        CHECK (operation IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT ck_policy_change_audits_snapshots CHECK (
        (operation = 'CREATE' AND before_name IS NULL AND after_name IS NOT NULL)
        OR (operation = 'UPDATE' AND before_name IS NOT NULL AND after_name IS NOT NULL)
        OR (operation = 'DELETE' AND before_name IS NOT NULL AND after_name IS NULL)
    )
);

CREATE INDEX ix_policy_change_audits_policy_time
    ON policy_change_audits (policy_id, changed_at DESC, id DESC);
