server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: zero-trust-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/zerotrust}
    username: ${DB_USERNAME:zerotrust}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      show-details: never
